[package]
name = "vanillachat"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-control-codes = { version = "1.0.1", features = ["parser"] }
nix = { version = "0.30.1", features = ["poll"] }
termios = "0.3.3"
